language: node_js # 设置语言

node_js: v10.15.3 # 设置相应版本

cache:
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - npm install hexo-cli -g

install:
    - npm install # 安装hexo及插件

script:
    - hexo clean # 清除
    - hexo generate
    # - hexo deploy

after_success:
    sed -i'' "s~git@github.com:~https://s~git@github.com:~https://${blog_token}@github.com/~"
    - hexo deploy > /dev/null

branches:
    only:
        - hexo # 只监测hexo分支

env:
    global:
        - GH_REF: github.com/Alexiusy/alexiusy.github.io.git #设置GH_REF，注意更改成自己的仓库地址
