language: node_js

node_js: stable

branches:
  only:
  - hexo      # 监视github仓库中的hexo分支，分支出现变化就执行build

before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli

install:
- npm install

script:
- cd ./Blog
# - git submodule init      # 用于更新主题,更新源为自己的主题项目，否则会clone最新NexT主题，而官方主题配置文件没有设置
# - git submodule update
- hexo clean && hexo g


after_success:
- git config --global user.name "Zeacone"
- git config --global user.email "andreboot42@gmail.com"
- hexo deploy